import {
  ABOUT_ROUTE,
  ADMIN_ROUTE,
  COMPARE_ROUTE,
  PROFILE_ROUTE,
  LOGIN_ROUTE,
  REGISTRATION_ROUTE,
  HOME_ROUTE,
} from "./constants";

export const pathSideBar = [
  COMPARE_ROUTE,
  PROFILE_ROUTE,
  ADMIN_ROUTE,
  ABOUT_ROUTE,
  LOGIN_ROUTE,
  REGISTRATION_ROUTE,
  HOME_ROUTE,
];
